---
- hosts: all

  vars:
    apt_file: /etc/apt/sources.list.d/google-chrome.list
    user: vagrant
    zsh_theme: steeef
    worblehat_db: worblehat_test
    worblehat_user: worblehat
    docker_compose_version: 1.21.2
    docker_compose_bin: /usr/local/bin/docker-compose

  tasks:
    # Adding google chrome 
    - name: Does the Google apt file exist?
      become: True
      command: test -f {{ apt_file }}
      register: google_apt_exists
      ignore_errors: True

    - name: Add Google Chrome key
      become: True
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      when: google_apt_exists.rc == 1

    - name: Add Google Chrome repo
      become: True
      shell: echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
      when: google_apt_exists.rc == 1

    - name: Update apt cache
      become: True
      apt: update_cache=yes
      when: google_apt_exists.rc == 1

    - name: Install Google Chrome
      become: True
      apt: pkg=google-chrome-stable state=present

    - name: add openjdk repo to enable download of openjdk-8
      become: True
      apt_repository:
        repo=ppa:openjdk-r/ppa
        state=present
    
    - name: add intellj repo
      become: True
      apt_repository:
        repo=ppa:mmk2410/intellij-idea
        state=present

    #Configuring java
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: 
        name: [oracle-java8-installer, ca-certificates, oracle-java8-set-default]
        state: latest

    #Adding additional requirements
    - name: install zsh, git, curl, maven, vim, mysql-server, python-mysqldb, xterm
      become: True
      apt:
        name : [zsh, git, maven, gradle, vim, mysql-server, python-mysqldb, xterm, intellij-idea-community, language-pack-de]
        #ubuntu-gnome-desktop]
        update_cache: yes
    
    - name: install German language
      become: true
      apt:
        name: [wngerman, wswiss, gnome-user-docs-de, libreoffice-l10n-de, hunspell-de-ch-frami, language-pack-gnome-de, hunspell-de-de-frami, mythes-de-ch, wogerman,
                hyphen-de, firefox-locale-de, hunspell-de-at-frami, thunderbird-locale-de, mythes-de ,libreoffice-help-de, gnome-getting-started-docs-de]
    
    - name: Ensure a locale exists
      locale_gen:
        name: de_DE.UTF-8
        state: present


    #Shell beautification
    - name: Clone oh-my-zsh repo
      become: True
      git: 
        repo: https://github.com/robbyrussell/oh-my-zsh.git 
        dest: /home/{{ user }}/.oh-my-zsh
        clone: yes

    - name: Set zsh as default shell
      become: True
      user: name={{ user }} shell=/bin/zsh

    - name: Create conf folder in home directory
      file: path=/home/{{ user }}/conf state=directory owner={{ user }}

    - name: deploy .zshrc
      template: src=files/zshrc.sh dest=/home/{{ user }}/conf/zshrc owner={{ user }}

    - name: remove standard zshrc
      file: path=/home/{{ user }}/.zshrc state=absent

    - name: symlink zshrc
      file: path=/home/{{ user }}/.zshrc src=/home/{{ user }}/conf/zshrc state=link owner={{ user }}


    
    #      - name: set global path to java 8 in /etc/profile
    #  lineinfile:
    #    dest=/etc/profile
    #    line="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
    #    state=present

    #- name: set java to java 8
    #  become: True
    #  shell: update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64

    - name: Add Docker GPG key
      become: True
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      become: True
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      become: True
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
        state: present
        update_cache: yes

    - name: Ensure docker deamon is running
      become: True
      service:
        name: docker
        state: started
      become: true

    - name: Add vagrant as docker user
      shell: usermod -aG docker {{ user }}
      become: True

    - name: Install docker-compose
      become: True
      apt:
        name: docker-compose
        state: present
        update_cache: yes
   
    #Create Database for worblehat
    # - name: 3. Set MySQL root password before installing
    #   become: True
    #   debconf: name='mysql-server' question='mysql-server/root_password' value='wordpass'
    #   debconf: name='mysql-server' question='mysql-server/root_password_again' value='wordpass' vtype='password'

    
    # - name: create empty Worblehat database
    #   become: True
    #   mysql_db:
    #     login_user: 'root'
    #     login_password: 'wordpass'
    #     name: "{{ worblehat_db }}"
    #     state: present

    # - name: create Worblehat database user
    #   mysql_user:
    #     name={{ worblehat_user }}
    #     password={{ worblehat_user }}
    #     state=present
    #     priv={{ worblehat_db }}.*:ALL

    - name: Change timezone
      become: True
      shell: timedatectl set-timezone Europe/Berlin

  roles:
    - role: gantsign.keyboard
      # The XKB keyboard model name.
      keyboard_model: pc104

      # The XKB keyboard layout name.
      keyboard_layout: de

      # The XKB keyboard variant components.
      keyboard_variant: ''

      # The XKB keyboard option components.
      keyboard_options: ''

      # The behavior of <BackSpace> and <Delete> keys.
      keyboard_backspace: guess